inherit_from:
  - .rubocop_airbnb.yml

Airbnb/ModuleMethodInWrongFile:
  Description: Define a module method in the file that defines the module, not a file that happens to use the module as a namespace.
  Enabled: false
  Include:
  - 'app/**/*'
  - 'lib/**/*'
  
AllCops:
  Exclude:
    - 'db/**/*'
    - 'bin/*'
    - 'config/environments/*'
    - 'config/application.rb'
    - 'config/initializers/*'
    - 'config/spring.rb'
    - 'lib/tasks/*'
    - 'vendor/**/*'
    - 'path/ruby'
    - 'Gemfile'
    - 'spec/spec_helper.rb'
    - 'spec/rails_helper.rb'
    - 'app/uploaders/user_icon_uploader.rb'
